<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="79" started-at="2022-01-18T07:46:37 IST" finished-at="2022-01-18T07:46:37 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="79" started-at="2022-01-18T07:46:37 IST" finished-at="2022-01-18T07:46:37 IST">
      <class name="com.Sample.com.Sample.ExceptionHandleExampleTest">
        <test-method status="PASS" signature="testTest1()[pri:0, instance:com.Sample.com.Sample.ExceptionHandleExampleTest@7f13d6e]" name="testTest1" duration-ms="13" started-at="2022-01-18T07:46:37 IST" finished-at="2022-01-18T07:46:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTest1 -->
      </class> <!-- com.Sample.com.Sample.ExceptionHandleExampleTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
